
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class three extends javax.swing.JFrame {

    private String startGame = "X";
            private int xCount = 0;
            private int oCount = 0;
            
    /**
     * Creates new form three
     */
    public three() {
        initComponents();
    }

    /*
    private void gameScore()
    {
    playerx.setText(string.valueof(xCount));
     playero.setText(string.valueof(oCount));
    }
    */
    
    /**
     * 
  
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void choose_a_Player()
    {
    if(startGame.equalsIgnoreCase("X"))
    {
        startGame = "O";
    }
    else
    {
    startGame = "X";
    }
    }
    
    
    private void WinningGame()
    {
    String b1 = txtbtn1.getText();
    String b2 = txtbtn2.getText();
    String b3 = txtbtn3.getText();
      
    String b4 = txtbtn4.getText();
    String b5 = txtbtn5.getText();
    String b6 = txtbtn6.getText();
         
    String b7 = txtbtn7.getText();
    String b8 = txtbtn8.getText();
    String b9 = txtbtn9.getText();
            
            //for player X
if(b1 == ("X") && b2 == ("X") && b3 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn1.setBackground(Color.ORANGE);
txtbtn2.setBackground(Color.ORANGE);
txtbtn3.setBackground(Color.ORANGE);
}

if(b4 == ("X") && b5 == ("X") && b6 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn4.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn6.setBackground(Color.ORANGE);
}
            
if(b7 == ("X") && b8 == ("X") && b9 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn7.setBackground(Color.ORANGE);
txtbtn8.setBackground(Color.ORANGE);
txtbtn9.setBackground(Color.ORANGE);
}

if(b1 == ("X") && b4 == ("X") && b7 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn1.setBackground(Color.ORANGE);
txtbtn4.setBackground(Color.ORANGE);
txtbtn7.setBackground(Color.ORANGE);
}

if(b2 == ("X") && b5 == ("X") && b8 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn2.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn8.setBackground(Color.ORANGE);
}

if(b3 == ("X") && b6 == ("X") && b9 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn3.setBackground(Color.ORANGE);
txtbtn6.setBackground(Color.ORANGE);
txtbtn9.setBackground(Color.ORANGE);
}

if(b1 == ("X") && b5 == ("X") && b9 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn1.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn9.setBackground(Color.ORANGE);
}

if(b3 == ("X") && b5 == ("X") && b7 == ("X"))
{
JOptionPane.showMessageDialog(this,"player X wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn3.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn7.setBackground(Color.ORANGE);
}

if(b1 == ("O") && b2 == ("O") && b3 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn1.setBackground(Color.ORANGE);
txtbtn2.setBackground(Color.ORANGE);
txtbtn3.setBackground(Color.ORANGE);
}

if(b4 == ("O") && b5 == ("O") && b6 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn4.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn6.setBackground(Color.ORANGE);
}

if(b7 == ("O") && b8 == ("O") && b9 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn7.setBackground(Color.ORANGE);
txtbtn8.setBackground(Color.ORANGE);
txtbtn9.setBackground(Color.ORANGE);
}

if(b1 == ("O") && b4 == ("O") && b7 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn1.setBackground(Color.ORANGE);
txtbtn4.setBackground(Color.ORANGE);
txtbtn7.setBackground(Color.ORANGE);
}

if(b2 == ("O") && b5 == ("O") && b8 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn2.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn8.setBackground(Color.ORANGE);
}


if(b3 == ("O") && b6 == ("O") && b9 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn3.setBackground(Color.ORANGE);
txtbtn6.setBackground(Color.ORANGE);
txtbtn9.setBackground(Color.ORANGE);
}

if(b1 == ("O") && b5 == ("O") && b9 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn1.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn9.setBackground(Color.ORANGE);
}

if(b3 == ("O") && b5 == ("O") && b7 == ("O"))
{
JOptionPane.showMessageDialog(this,"player O wins","TIC TAC TOE",JOptionPane.INFORMATION_MESSAGE);
xCount++;

txtbtn3.setBackground(Color.ORANGE);
txtbtn5.setBackground(Color.ORANGE);
txtbtn7.setBackground(Color.ORANGE);
}
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        txtbtn1 = new javax.swing.JButton();
        txtbtn2 = new javax.swing.JButton();
        txtbtn3 = new javax.swing.JButton();
        txtbtn4 = new javax.swing.JButton();
        txtbtn5 = new javax.swing.JButton();
        txtbtn6 = new javax.swing.JButton();
        txtbtn7 = new javax.swing.JButton();
        txtbtn8 = new javax.swing.JButton();
        txtbtn9 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(124, 189, 254));
        setForeground(new java.awt.Color(254, 91, 91));

        txtbtn1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn1.setPreferredSize(new java.awt.Dimension(120, 120));
        txtbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn1ActionPerformed(evt);
            }
        });

        txtbtn2.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn2.setMaximumSize(new java.awt.Dimension(120, 120));
        txtbtn2.setPreferredSize(new java.awt.Dimension(120, 120));
        txtbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn2ActionPerformed(evt);
            }
        });

        txtbtn3.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn3.setPreferredSize(new java.awt.Dimension(120, 120));
        txtbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn3ActionPerformed(evt);
            }
        });

        txtbtn4.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn4ActionPerformed(evt);
            }
        });

        txtbtn5.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn5ActionPerformed(evt);
            }
        });

        txtbtn6.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn6ActionPerformed(evt);
            }
        });

        txtbtn7.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn7.setMaximumSize(new java.awt.Dimension(120, 120));
        txtbtn7.setPreferredSize(new java.awt.Dimension(120, 120));
        txtbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn7ActionPerformed(evt);
            }
        });

        txtbtn8.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn8ActionPerformed(evt);
            }
        });

        txtbtn9.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtn9ActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(90, 172, 255));
        jPanel11.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel11.setForeground(new java.awt.Color(177, 0, 0));

        jLabel2.setFont(new java.awt.Font("Yrsa Medium", 1, 48)); // NOI18N
        jLabel2.setText("3x3");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setFont(new java.awt.Font("TlwgTypewriter", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(136, 253, 88));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn2ActionPerformed

txtbtn2.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn2.setForeground(Color.RED);
    }
    else
    {
    txtbtn2.setForeground(Color.MAGENTA);
    }  
        choose_a_Player();
        WinningGame();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbtn2ActionPerformed

    private void txtbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn8ActionPerformed
txtbtn8.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn8.setForeground(Color.RED);
    }
    else
    {
    txtbtn8.setForeground(Color.MAGENTA);
    }  
        choose_a_Player(); 
        WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JFrame frame = new JFrame("Exit");

if(JOptionPane.showConfirmDialog(frame,"confirm if you want to exit !",
        "TIC TAC TOE",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
{
System.exit(0);
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn1ActionPerformed
txtbtn1.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn1.setForeground(Color.RED);
    }
    else
    {
    txtbtn1.setForeground(Color.MAGENTA);
    }  
        choose_a_Player();
        WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn1ActionPerformed

    private void txtbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn3ActionPerformed
txtbtn3.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn3.setForeground(Color.RED);
    }
    else
    {
    txtbtn3.setForeground(Color.MAGENTA);
    }  
        choose_a_Player();
         WinningGame();

        // TODO add your handling code here:
    }//GEN-LAST:event_txtbtn3ActionPerformed

    private void txtbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn4ActionPerformed
txtbtn4.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn4.setForeground(Color.RED);
    }
    else
    {
    txtbtn4.setForeground(Color.MAGENTA);
    }  
        choose_a_Player();  
         WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn4ActionPerformed

    private void txtbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn5ActionPerformed
txtbtn5.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn5.setForeground(Color.RED);
    }
    else
    {
    txtbtn5.setForeground(Color.MAGENTA);
    }  
        choose_a_Player(); 
         WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn5ActionPerformed

    private void txtbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn6ActionPerformed
txtbtn6.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn6.setForeground(Color.RED);
    }
    else
    {
    txtbtn6.setForeground(Color.MAGENTA);
    }  
        choose_a_Player(); 
         WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn6ActionPerformed

    private void txtbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn7ActionPerformed
txtbtn7.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn7.setForeground(Color.RED);
    }
    else
    {
    txtbtn7.setForeground(Color.MAGENTA);
    }  
        choose_a_Player(); 
         WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn7ActionPerformed

    private void txtbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtn9ActionPerformed
txtbtn9.setText(startGame);
        if(startGame.equalsIgnoreCase("X"))
    {
        txtbtn9.setForeground(Color.RED);
    }
    else
    {
    txtbtn9.setForeground(Color.MAGENTA);
    }  
        choose_a_Player(); 
         WinningGame();// TODO add your handling code here:
    }//GEN-LAST:event_txtbtn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new three().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JButton txtbtn1;
    private javax.swing.JButton txtbtn2;
    private javax.swing.JButton txtbtn3;
    private javax.swing.JButton txtbtn4;
    private javax.swing.JButton txtbtn5;
    private javax.swing.JButton txtbtn6;
    private javax.swing.JButton txtbtn7;
    private javax.swing.JButton txtbtn8;
    private javax.swing.JButton txtbtn9;
    // End of variables declaration//GEN-END:variables
}
